#= require modernizr
#= require jquery
#= require jquery_ujs
#= require handlebars
#= require ember
#= require ember-data
#= require_self
#= require beech_server
BeechServer = Ember.Application.create()
